import { ILink } from '@models/link.model';

export const links: ILink[] = [
  {
    id: 1,
    title: 'LinkedIn',
    url: 'https://linkedin.com/in/ArshdeepGrover',
    icon: '💼',
    category: 'professional',
    description: 'Connect with me on LinkedIn',
    show: true,
  },
  {
    id: 2,
    title: 'GitHub',
    url: 'https://github.com/ArshdeepGrover',
    icon: '🐙',
    category: 'professional',
    description: 'Check out my open source projects',
    show: true,
  },
  {
    id: 3,
    title: 'GitLab',
    url: 'https://gitlab.com/ArshdeepGrover',
    icon: '🦊',
    category: 'professional',
    description: 'View my GitLab repositories',
    show: true,
  },
  {
    id: 4,
    title: 'Medium',
    url: 'https://medium.com/@ArshdeepGrover',
    icon: '✍️',
    category: 'content',
    description: 'Read my technical blog posts',
    show: true,
  },
  {
    id: 5,
    title: 'Dev.to',
    url: 'https://dev.to/arshdeepgrover',
    icon: '👩‍💻',
    category: 'content',
    description: 'Developer articles and tutorials',
    show: true,
  },
  {
    id: 6,
    title: 'Stack Overflow',
    url: 'https://stackoverflow.com/users/19189914/arshdeep-singh',
    icon: '📚',
    category: 'professional',
    description: 'My Stack Overflow profile',
    show: true,
  },
  {
    id: 7,
    title: 'X / Twitter',
    url: 'https://x.com/ArshdeepGroverS',
    icon: '🐦',
    category: 'social',
    description: 'Follow me on X',
    show: true,
  },
  {
    id: 8,
    title: 'Topmate',
    url: 'https://topmate.io/arshdeepgrover',
    icon: '🤝',
    category: 'professional',
    description: 'Book a 1:1 session with me',
    show: true,
  },
  {
    id: 9,
    title: 'Calendly',
    url: 'https://calendly.com/arshdeepgrover',
    icon: '📅',
    category: 'professional',
    description: 'Schedule a meeting',
    show: true,
  },
  {
    id: 10,
    title: 'Portfolio',
    url: 'https://arshdeepsingh.info',
    icon: '🌐',
    category: 'other',
    description: 'My personal portfolio website',
    show: true,
  },
  {
    id: 11,
    title: 'Resume',
    url: 'https://arshdeepsingh.info/resume/Arshdeep_Singh_SoftwareDeveloper_Resume.pdf',
    icon: '📄',
    category: 'other',
    description: 'Download my resume',
    show: true,
  },
  {
    id: 12,
    title: 'Email',
    url: 'mailto:arsh199820@gmail.com',
    icon: '📧',
    category: 'other',
    description: 'Send me an email',
    show: true,
  },
];
