import { ILink } from '@models/link.model';

export const links: ILink[] = [
  {
    id: 1,
    title: 'LinkedIn',
    url: 'https://linkedin.com/in/ArshdeepGrover',
    icon: 'https://www.google.com/s2/favicons?domain=linkedin.com&sz=128',
    iconType: 'image',
    brandColor: '#0A66C2',
    category: 'professional',
    description: 'Connect with me on LinkedIn',
    show: true,
  },
  {
    id: 2,
    title: 'GitHub',
    url: 'https://github.com/ArshdeepGrover',
    icon: 'https://www.google.com/s2/favicons?domain=github.com&sz=128',
    iconType: 'image',
    brandColor: '#24292f',
    category: 'professional',
    description: 'Check out my open source projects',
    show: true,
  },
  {
    id: 3,
    title: 'GitLab',
    url: 'https://gitlab.com/ArshdeepGrover',
    icon: 'https://www.google.com/s2/favicons?domain=gitlab.com&sz=128',
    iconType: 'image',
    brandColor: '#FC6D26',
    category: 'professional',
    description: 'View my GitLab repositories',
    show: true,
  },
  {
    id: 4,
    title: 'Medium',
    url: 'https://medium.com/@ArshdeepGrover',
    icon: 'https://www.google.com/s2/favicons?domain=medium.com&sz=128',
    iconType: 'image',
    brandColor: '#00ab6c',
    category: 'content',
    description: 'Read my technical blog posts',
    show: true,
  },
  {
    id: 5,
    title: 'Dev.to',
    url: 'https://dev.to/arshdeepgrover',
    icon: 'https://www.google.com/s2/favicons?domain=dev.to&sz=128',
    iconType: 'image',
    brandColor: '#3b49df',
    category: 'content',
    description: 'Developer articles and tutorials',
    show: true,
  },
  {
    id: 6,
    title: 'Stack Overflow',
    url: 'https://stackoverflow.com/users/19189914/arshdeep-singh',
    icon: 'https://www.google.com/s2/favicons?domain=stackoverflow.com&sz=128',
    iconType: 'image',
    brandColor: '#F58025',
    category: 'professional',
    description: 'My Stack Overflow profile',
    show: true,
  },
  {
    id: 7,
    title: 'X / Twitter',
    url: 'https://x.com/ArshdeepGroverS',
    icon: 'https://www.google.com/s2/favicons?domain=x.com&sz=128',
    iconType: 'image',
    brandColor: '#1DA1F2',
    category: 'social',
    description: 'Follow me on X',
    show: true,
  },
  {
    id: 8,
    title: 'Topmate',
    url: 'https://topmate.io/arshdeepgrover',
    icon: 'https://www.google.com/s2/favicons?domain=topmate.io&sz=128',
    iconType: 'image',
    brandColor: '#1DBF73',
    category: 'professional',
    description: 'Book a 1:1 session with me',
    show: true,
  },
  {
    id: 9,
    title: 'Calendly',
    url: 'https://calendly.com/arshdeepgrover',
    icon: 'https://www.google.com/s2/favicons?domain=calendly.com&sz=128',
    iconType: 'image',
    brandColor: '#006BFF',
    category: 'professional',
    description: 'Schedule a meeting',
    show: true,
  },
  {
    id: 10,
    title: 'Portfolio',
    url: 'https://arshdeepsingh.info',
    icon: 'https://www.google.com/s2/favicons?domain=arshdeepsingh.info&sz=128',
    iconType: 'image',
    brandColor: '#FF7955',
    category: 'other',
    description: 'My personal portfolio website',
    show: true,
  },
  {
    id: 11,
    title: 'Commudle',
    url: 'https://www.commudle.com/users/ArshdeepGrover',
    icon: 'https://www.google.com/s2/favicons?domain=commudle.com&sz=128',
    iconType: 'image',
    brandColor: '#6366F1',
    category: 'professional',
    description: 'My Commudle community profile',
    show: true,
  },
  {
    id: 12,
    title: 'Unstop',
    url: 'https://unstop.com/mentor/ArshdeepGrover',
    icon: 'https://www.google.com/s2/favicons?domain=unstop.com&sz=128',
    iconType: 'image',
    brandColor: '#FF6B35',
    category: 'professional',
    description: 'Mentor profile on Unstop',
    show: true,
  },
  {
    id: 13,
    title: 'Resume',
    url: 'https://arshdeepsingh.info/resume/Arshdeep_Singh_SoftwareDeveloper_Resume.pdf',
    icon: 'file',
    iconType: 'svg',
    brandColor: '#FF7955',
    category: 'other',
    description: 'Download my resume',
    show: true,
  },
  {
    id: 14,
    title: 'Email',
    url: 'mailto:arsh199820@gmail.com',
    icon: 'https://www.google.com/s2/favicons?domain=gmail.com&sz=128',
    iconType: 'image',
    brandColor: '#EA4335',
    category: 'other',
    description: 'arsh199820@gmail.com',
    show: true,
  },
];
