import { ISkillCategory, IOtherTechnology } from '@models/skill.model';

export const skillCategories: ISkillCategory[] = [
  {
    name: 'Languages',
    description: 'The languages I write day to day',
    icon: '📝',
    skills: [
      {
        name: 'JavaScript',
        description: 'ES6+, async patterns, browser APIs',
        icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/javascript/javascript-original.svg',
        category: 'languages',
        proficiency: 'advanced',
      },
      {
        name: 'TypeScript',
        description: 'Interfaces, generics, strict compiler settings',
        icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/typescript/typescript-original.svg',
        category: 'languages',
        proficiency: 'advanced',
      },
      {
        name: 'Ruby',
        description: 'Idiomatic Ruby, gems, RSpec',
        icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/ruby/ruby-original.svg',
        category: 'languages',
        proficiency: 'advanced',
      },
      {
        name: 'SQL',
        description: 'Joins, aggregates, indexes, query plans',
        icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/postgresql/postgresql-original.svg',
        category: 'languages',
        proficiency: 'intermediate',
      },
      {
        name: 'HTML',
        description: 'Semantic markup and accessible structure',
        icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/html5/html5-original.svg',
        category: 'languages',
        proficiency: 'advanced',
      },
      {
        name: 'CSS / SCSS',
        description: 'Grid, flexbox, mixins, responsive layouts',
        icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/sass/sass-original.svg',
        category: 'languages',
        proficiency: 'advanced',
      },
    ],
  },
  {
    name: 'Frameworks & libraries',
    description: 'What I reach for when building a product',
    icon: '🧱',
    skills: [
      {
        name: 'Angular',
        description: 'Standalone components, RxJS, routing, forms',
        icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/angularjs/angularjs-original.svg',
        category: 'frameworks',
        proficiency: 'advanced',
      },
      {
        name: 'Ruby on Rails',
        description: 'REST APIs, ActiveRecord, background jobs',
        icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/rails/rails-plain.svg',
        category: 'frameworks',
        proficiency: 'advanced',
      },
      {
        name: 'Tailwind CSS',
        description: 'Utility-first styling with custom themes',
        icon: 'https://www.vectorlogo.zone/logos/tailwindcss/tailwindcss-icon.svg',
        category: 'frameworks',
        proficiency: 'advanced',
      },
      {
        name: 'Sanity',
        description: 'Headless CMS schemas and content workflows',
        icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/sanity/sanity-original.svg',
        category: 'frameworks',
        proficiency: 'intermediate',
      },
      {
        name: 'Nebular',
        description: 'Angular UI kit used across admin interfaces',
        icon: 'https://akveo.github.io/nebular/assets/img/akveo-logo.png',
        category: 'frameworks',
        proficiency: 'intermediate',
      },
      {
        name: 'Bootstrap',
        description: 'Component library and responsive grid',
        icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/bootstrap/bootstrap-original.svg',
        category: 'frameworks',
        proficiency: 'intermediate',
      },
    ],
  },
  {
    name: 'Practice',
    description: 'Problems I have solved more than once',
    icon: '🛠️',
    skills: [
      {
        name: 'Frontend performance',
        description: 'Bundle size, lazy loading, measured load times',
        icon: '⚡',
        category: 'practice',
        proficiency: 'advanced',
      },
      {
        name: 'Database & query optimisation',
        description: 'Schema design, indexing, slow query analysis',
        icon: '🗃️',
        category: 'practice',
        proficiency: 'intermediate',
      },
      {
        name: 'Payment integration',
        description: 'Razorpay, including e-mandate recurring billing',
        icon: '💳',
        category: 'practice',
        proficiency: 'advanced',
      },
      {
        name: 'Authentication',
        description: 'JWT, OTP login, TOTP two-factor auth',
        icon: '🔐',
        category: 'practice',
        proficiency: 'advanced',
      },
      {
        name: 'CI/CD',
        description: 'GitHub Actions pipelines for build and deploy',
        icon: '🔁',
        category: 'practice',
        proficiency: 'intermediate',
      },
      {
        name: 'Internationalisation',
        description: 'Multi-language interfaces, Hindi and English',
        icon: '🌐',
        category: 'practice',
        proficiency: 'intermediate',
      },
      {
        name: 'Code review & mentoring',
        description: 'Reviewing pull requests and growing developers',
        icon: '👀',
        category: 'practice',
        proficiency: 'advanced',
      },
      {
        name: 'Agile delivery',
        description: 'Sprint planning, estimation, release cadence',
        icon: '📋',
        category: 'practice',
        proficiency: 'advanced',
      },
    ],
  },
  {
    name: 'Tools',
    description: 'The rest of the workbench',
    icon: '🧰',
    skills: [
      {
        name: 'Git',
        description: 'Branching strategies, rebasing, conflict resolution',
        icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/git/git-original.svg',
        category: 'tools',
        proficiency: 'advanced',
      },
      {
        name: 'GitHub',
        description: 'Pull requests, Actions, project boards',
        icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/github/github-original.svg',
        category: 'tools',
        proficiency: 'advanced',
      },
      {
        name: 'GitLab',
        description: 'Merge requests and CI pipelines',
        icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/gitlab/gitlab-original.svg',
        category: 'tools',
        proficiency: 'intermediate',
      },
      {
        name: 'Figma',
        description: 'Working from designs and design handoff',
        icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/figma/figma-original.svg',
        category: 'tools',
        proficiency: 'intermediate',
      },
      {
        name: 'Google Tag Manager',
        description: 'Event tracking without redeploying the app',
        icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/google/google-original.svg',
        category: 'tools',
        proficiency: 'intermediate',
      },
      {
        name: 'Sentry',
        description: 'Error tracking and release monitoring',
        icon: 'https://www.vectorlogo.zone/logos/sentryio/sentryio-icon.svg',
        category: 'tools',
        proficiency: 'intermediate',
      },
      {
        name: 'AI coding agents',
        description: 'Agent configuration, documentation, team rollout',
        icon: '🤖',
        category: 'tools',
        proficiency: 'advanced',
      },
    ],
  },
  {
    name: 'Training & enablement',
    description: 'The teaching side of the same craft',
    icon: '🎓',
    skills: [
      {
        name: 'Workshop facilitation',
        description: 'Hands-on sessions for students and developers',
        icon: '🧑‍🏫',
        category: 'training',
        proficiency: 'intermediate',
      },
      {
        name: 'Training material development',
        description: 'Writing the material that goes with the session',
        icon: '📚',
        category: 'training',
        proficiency: 'intermediate',
      },
      {
        name: 'Technical onboarding',
        description: 'Getting teams productive with new tooling',
        icon: '🚀',
        category: 'training',
        proficiency: 'intermediate',
      },
      {
        name: 'Email marketing fundamentals',
        description: 'Campaign basics, segmentation, measurement',
        icon: '✉️',
        category: 'training',
        proficiency: 'intermediate',
      },
    ],
  },
];

export const otherTechnologies: IOtherTechnology[] = [
  {
    name: 'Node.js',
    icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nodejs/nodejs-original.svg',
  },
  {
    name: 'PostgreSQL',
    icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/postgresql/postgresql-original.svg',
  },
  {
    name: 'Three.js',
    icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/threejs/threejs-original.svg',
  },
  {
    name: 'Firebase',
    icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/firebase/firebase-plain.svg',
  },
  {
    name: 'Material UI',
    icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/materialui/materialui-original.svg',
  },
  {
    name: 'Postman',
    icon: 'https://www.vectorlogo.zone/logos/getpostman/getpostman-icon.svg',
  },
  {
    name: 'Ubuntu',
    icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/ubuntu/ubuntu-plain.svg',
  },
  {
    name: 'Markdown',
    icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/markdown/markdown-original.svg',
  },
  {
    name: 'Vercel',
    icon: 'https://www.vectorlogo.zone/logos/vercel/vercel-icon.svg',
  },
  {
    name: 'Netlify',
    icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/netlify/netlify-original.svg',
  },
  {
    name: 'NPM',
    icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/npm/npm-original-wordmark.svg',
  },
  {
    name: 'Google Analytics',
    icon: 'https://www.vectorlogo.zone/logos/google_analytics/google_analytics-icon.svg',
  },
];
