import { IPortfolioProject } from '@models/portfolio-project.model';

export const portfolioProjects: IPortfolioProject[] = [
  {
    id: 1,
    title: 'Finova Banking App',
    shortDescription: 'A modern digital banking experience redesigned for millennials.',
    description: 'Complete redesign of a digital banking platform focusing on simplicity, security, and a seamless mobile-first experience for the next generation of banking users.',
    category: 'product',
    image: '/images/projects/finova.png',
    technologies: ['Figma', 'Angular', 'Tailwind CSS', 'Node.js'],
    liveUrl: '#',
    challenge: 'The existing banking app had a 68% drop-off rate during onboarding due to a complex, outdated interface that confused younger users.',
    solution: 'We redesigned the entire user journey with a mobile-first approach, simplified onboarding to 3 steps, and introduced a clean, modern visual language with intuitive navigation.',
    results: ['45% increase in user retention', '3x faster onboarding completion', '4.8★ App Store rating'],
  },
  {
    id: 2,
    title: 'Bloom E-Commerce',
    shortDescription: 'Premium e-commerce platform for a sustainable fashion brand.',
    description: 'A full e-commerce web design for an eco-friendly fashion brand, combining stunning visuals with conversion-optimized shopping experiences.',
    category: 'web',
    image: '/images/projects/bloom.png',
    technologies: ['Figma', 'Next.js', 'Stripe', 'Tailwind CSS'],
    liveUrl: '#',
    challenge: 'The brand needed an online presence that reflected their sustainability values while maintaining a premium, high-conversion shopping experience.',
    solution: 'We designed an immersive storefront with earthy tones, smooth animations, and a streamlined checkout flow. Every element reinforces the brand\'s eco-conscious identity.',
    results: ['120% increase in online sales', '35% lower cart abandonment', 'Featured in Awwwards'],
  },
  {
    id: 3,
    title: 'Zenith SaaS Dashboard',
    shortDescription: 'Analytics dashboard for a B2B SaaS platform.',
    description: 'A comprehensive analytics dashboard design for a SaaS product, featuring real-time data visualization, customizable widgets, and role-based views.',
    category: 'product',
    image: '/images/projects/zenith.png',
    technologies: ['Figma', 'Angular', 'D3.js', 'Material Design'],
    liveUrl: '#',
    challenge: 'Enterprise users struggled with information overload — the existing dashboard displayed too much data without clear hierarchy or actionable insights.',
    solution: 'We created a modular, widget-based dashboard with smart defaults, role-specific views, and progressive disclosure of data. Key metrics are surfaced upfront with drill-down capabilities.',
    results: ['60% faster task completion', '90% user satisfaction score', 'Reduced support tickets by 40%'],
  },
  {
    id: 4,
    title: 'Artisan Studio Branding',
    shortDescription: 'Complete brand identity for a creative agency.',
    description: 'Full brand identity design including logo, color system, typography, stationery, and brand guidelines for a boutique creative agency.',
    category: 'branding',
    image: '/images/projects/artisan.png',
    technologies: ['Illustrator', 'Photoshop', 'Figma', 'After Effects'],
    liveUrl: '#',
    challenge: 'The agency needed a distinctive brand identity that stood out in a crowded market while conveying creativity, professionalism, and innovation.',
    solution: 'We developed a bold, geometric brand mark with a vibrant color palette and custom typography. The brand system is flexible enough for digital and print applications.',
    results: ['Brand recognition increased by 80%', 'Consistent identity across 15+ touchpoints', 'Client acquisition up 50%'],
  },
  {
    id: 5,
    title: 'TravelMate Booking Platform',
    shortDescription: 'Travel booking website with immersive visual storytelling.',
    description: 'A travel booking platform that combines beautiful destination imagery with a frictionless booking experience, designed to inspire wanderlust and drive conversions.',
    category: 'web',
    image: '/images/projects/travelmate.png',
    technologies: ['Figma', 'React', 'Mapbox', 'Tailwind CSS'],
    liveUrl: '#',
    challenge: 'Users found the existing booking flow tedious and uninspiring, leading to high abandonment rates and low repeat bookings.',
    solution: 'We redesigned the platform with full-bleed imagery, an interactive map-based search, and a streamlined 2-step booking process. Visual storytelling drives engagement at every touchpoint.',
    results: ['200% increase in bookings', '55% more returning users', 'Average session time up 3x'],
  },
  {
    id: 6,
    title: 'Pulse Fitness Brand',
    shortDescription: 'Energetic brand identity for a fitness tech startup.',
    description: 'Dynamic brand identity for a fitness technology startup, featuring bold visuals, energetic typography, and a versatile design system for digital and physical products.',
    category: 'branding',
    image: '/images/projects/pulse.png',
    technologies: ['Illustrator', 'Figma', 'After Effects', 'Photoshop'],
    liveUrl: '#',
    challenge: 'The startup needed a brand that conveyed energy and innovation while appealing to both casual fitness enthusiasts and serious athletes.',
    solution: 'We crafted a dynamic brand identity with angular forms, a high-energy color palette of electric gradients, and motion-ready assets. The system scales from app icons to billboard ads.',
    results: ['Successful Series A with brand deck', '10K+ app downloads in first month', 'Strong social media brand presence'],
  },
];
